### ISSUE TITLE
NOT OPEN PVE VDI

### ISSUE THREAD

**Issue by didalexh** [joshpatten/PVE-VDIClient#7]
1. I INSTALL PVE VDI 
2. IN Program Files\VDIClient  ADD  vdiclient.ini 
3. CLICK vdiclient.exe
4. IT NOT WORK SEND
![NOT](https://user-images.githubusercontent.com/87248646/161790688-db2e7a3b-3bc8-46b2-ad73-87f545e53e9f.JPG)

**Comment by jpattWPC** [comment]
![image](https://user-images.githubusercontent.com/16338864/161792429-dfbdeb8b-6a49-422c-b5e2-a33d4a299413.png)
This error only occurs if it can't find the files in either the %APPDATA% or %PROGRAMFILES% location,

Please open a command prompt and post the output of the following 2 commands:

    echo %PROGRAMFILES%
    echo %APPDATA%

Also, if you installed the VDI Client in a location other than the default you will have to use the APPDATA config file location rather than the location where you installedf VDI Client.

**Comment by walstib2** [comment]
I ended up having to put vdiclient  in the VDICLIENT folder in APPDATA  ( had to create the folder)

So it looks like : C:\Users\walstib2\AppData\Roaming\VDIClient\vdiclient.ini

**Comment by z0kuoo** [comment]
> 1. I INSTALL PVE VDI
> 2. IN Program Files\VDIClient  ADD  vdiclient.ini
> 3. CLICK vdiclient.exe
> 4. IT NOT WORK SEND
>    ![NOT](https://user-images.githubusercontent.com/87248646/161790688-db2e7a3b-3bc8-46b2-ad73-87f545e53e9f.JPG)

I have the same problem, how did you solve it? can share

**Comment by joshpatten** [comment]
Are you running the latest release? This issue was fixed in some of the
more recent releases. You did ensure that your vdiclient.ini file exists in
one of the locations in the documentation, correct?
